name: Build and Deploy to Azure (Terraform + Function App + Web App)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './redditIngestFunc'
  FUNCTIONAPP_NAME: 'propjetocloudfunctionapp'
  REGISTRY: docker.io
  IMAGE_NAME: rodrig0salv/minha-app
  TAG: latest
  PLATFORM: linux/amd64
  WEBAPP_NAME: 'reddit-app'
  TERRAFORM_DIR: './infra'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Criar Storage Account e container 'tfstate' se necessário
        run: |
          echo "Verificar e criar Storage Account e container se necessário..."

          # Verificar se o Resource Group existe
          RG_EXISTS=$(az group exists --name terraform-cloud)

          if [ "$RG_EXISTS" = "false" ]; then
            echo "A criar Resource Group..."
            az group create \
              --name terraform-cloud \
              --location northeurope
          fi

          # Verificar se o Storage Account já existe
          ACCOUNT_EXISTS=$(az storage account check-name --name storageprojetocloud --query "nameAvailable" -o tsv)

          if [ "$ACCOUNT_EXISTS" = "false" ]; then
            echo "Storage Account já existe."
          else
            echo "A criar Storage Account..."
            az storage account create \
              --name storageprojetocloud \
              --resource-group terraform-cloud \
              --location northeurope \
              --sku Standard_LRS
          fi

          # Criar o container tfstate (o comando é idempotente)
          echo "A criar container 'tfstate' (se ainda não existir)..."
          az storage container create \
            --name tfstate \
            --account-name storageprojetocloud \
            --auth-mode login \
            --public-access off

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Plano Terraform
        run: terraform plan
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Validar Terraform
        run: terraform validate
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: ${{ env.TERRAFORM_DIR }}


  build:
    runs-on: ubuntu-latest
    needs: terraform
    permissions:
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Criar e ativar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependências da Function
        run: |
          pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      - name: Zip Function App
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip .

      - name: Guardar Function App como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_05F08B3D5D3A42788F364682EB18570A }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_3C476478AD3749ADBF692BA277661C71 }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Recuperar artefacto da Function App
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Descompactar Function App
        run: unzip release.zip -d ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Adicionar CORS à Function App (https://portal.azure.com)
        run: |
          az functionapp cors add \
            --name ${{ env.FUNCTIONAPP_NAME }} \
            --resource-group terraform-cloud \
            --allowed-origins https://portal.azure.com

      - name: Instalar Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Instalar dependências da Function App (no deploy)
        run: |
          pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      - name: Fazer deploy da Function App
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          func azure functionapp publish ${{ env.FUNCTIONAPP_NAME }} --python --force

      - name: Deploy da Web App (Docker)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
