name: Build & Deploy Container to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Variáveis de ambiente globais
env:
  REGISTRY: docker.io
  IMAGE_NAME: rodrig0salv/minha-app
  TAG: latest
  PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AzureAppService_ContainerUsername_05f08b3d5d3a42788f364682eb18570a }}
          password: ${{ secrets.AzureAppService_ContainerPassword_3c476478ad3749adbf692ba277661c71 }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: reddit-app
          slot-name: production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_59513a348e4a48a5998c742cc5a34bc8 }}
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
