name: Build and deploy container app to Azure Web App - reddit-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push container image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: ./web-app
        file: ./web-app/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/minha-app-reddit:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: reddit-app
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0ac9c24ed9d49e788a90a2ea61a8596 }}
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/minha-app-reddit:${{ github.sha }}
