name: Build e deploy de container para Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.AzureAppService_ContainerUsername_05f08b3d5d3a42788f364682eb18570a }}
          password: ${{ secrets.AzureAppService_ContainerPassword_3c476478ad3749adbf692ba277661c71 }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          registry: docker.io
          tags: |
            rodrig0salv/minha-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy para Azure Web App
        id: deploy-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: reddit-app
          slot-name: production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_59513a348e4a48a5998c742cc5a34bc8 }}
          images: |
            rodrig0salv/minha-app:latest
